experiment:
  name: "baseline_detr"
  seed: 42

model:
  architecture: "detr"
  name_or_path: "facebook/detr-resnet-50"
  num_labels: 91
  inference_threshold: 0.9

dataset:
  train_path: "data/train"
  val_path: "data/val"
  image_size: 480

training:
  learning_rate: 0.0001
  batch_size: 4
  weight_decay: 0.0001
  epochs: 5