experiment:
  name: "final_master_model"
  seed: 42

model:
  architecture: "yolos"
  name_or_path: "hustvl/yolos-tiny"
  num_labels: 91
  inference_threshold: 0.9
  freeze_backbone: true

dataset:
  train_path: "data/train"
  val_path: "data/val"
  image_size: 224

training:
  learning_rate: 0.00006
  batch_size: 2
  weight_decay: 0.0001
  epochs: 5